
global_template = "The following is a conversation between a human and an AI Chatbot. The AI assistant gives helpful, detailed, and polite answers to the user's questions.\n[|Human|]:{demon1}\n[|AI|]:{summary1}\n[|Human|]:{demon2}\n[|AI|]:{summary2}\n[|Human|]:{input}\n[|AI|]:" #global instructions with two demonstrationsglobal_no_demon_template_yulan = "The following is a conversation between a human and an AI assistant namely YuLan, developed by GSAI, Renmin University of China.The AI assistant gives helpful, detailed, and polite answers to the user's questions.\n[|Human|]:{input}\n[|AI|]:"#global instructions without demonstrations 
global_no_demon_template = "다음은 인간과 AI 챗봇 간의 대화입니다. AI 어시스턴트가 사용자의 질문에 대해 유용하고 상세하며 정중한 답변을 제공합니다.\n[|Human|]:{input}\n[|AI|]:"
global_no_demon_template = "The following is a conversation between a human and an AI Chatbot specialized in Football related information. The AI assistant gives helpful, detailed, and polite answers to the user's questions.\n[|Human|]:{input}\n[|AI|]:"#global instructions without demonstrations 

request_rewriting_template = '이제 축구 관련 지식 전문가로서 당신의 임무는 사용자가 실제로 말하고자 하는 바를 이해하는 것입니다. 사용자와 대화하는 과정에서 사용자는 일관성 있는 일련의 요청을 하지만, 한 요청의 주어나 대명사 또는 다른 부분이 누락되어 이전 요청에 나타날 수 있으므로 요청 자체가 완전하고 명확하지 않을 수 있습니다. 따라서 이제 이전 요청을 이해하여 사용자의 현재 질문 요청을 완성하는 것은 여러분의 몫입니다. 사용자 과거 요청은 : {history}이고 사용자 현재 요청은 : {request}입니다. 사용자 현재 요청의 의미가 완전하고 명확하도록 다시 작성해 주세요. 마지막으로 추가 설명이나 중간 과정 없이 재작성된 요청만 출력됩니다. 한글로 출력해 주세요. 재작성된 요청은 다음과 같습니다:'
request_rewriting_template = 'Your job now, as an expert on football related knowledge, is to understand what the user is really trying to say. In the course of a conversation with you, the user makes a series of requests that are coherent, but the requests themselves may not be complete and clear because the subject or pronoun or other parts of one request may be missing and appear in the previous requests. Therefore, it is now up to you to complete the user current question request by understanding historical request. The user historical requests were :{history}, and the user current request is : {request}. Please rewrite the user current request so that its meaning is complete and clear. Finally, only a rewritten request is printed, without any additional explanation or intermediate process. All your responses should be in Korean. The rewritten request is:'#passage extraction instructions

passage_extraction_template = "주어진 문서에서 쿼리와 관련된 문서 조각을 선택하여 출력하세요. 문서는 세 개의 대괄호 [[[]]]로 구분됩니다. 쿼리는 세 개의 괄호((())로 구분됩니다.) 출력은 문서의 요약이 아니라 원본 문서의 조각이어야 합니다. 문서에 쿼리와 관련된 조각이 없는 경우 아무것도 출력하지 마세요. 문서 내용: [[[{content}]]], 쿼리:((({question}))), 관련 문서 조각:"
passage_extraction_template = "From the given content, please select and output the relevant document fragments which include the most relevant information to the query. Note that the extracted fragment will be further used as references to answer the query. Therefore, each fragment should include all necessary information related to query. The document is delimited by triple brackets [[[]]]. The query is delimited by triple parentheses ((())). Note that the output must be fragments of the original document, not a summary of the document. Therefore, do not add any sentences in addition to the original fragment. If there is no fragment related to the query in the document, please output nothing. Answer in Korean. Document content: [[[{content}]]], query:((({question}))), relevant document fragments:"#passage extraction instruction 

answer_generation_template = "이제 다음 참고 자료를 바탕으로 질문에 보다 간결하고 전문적으로 답변해 주세요. 참조는 세 개의 대괄호 [[[]]]로 구분됩니다. 쿼리는 세 개의 괄호((())로 구분됩니다.). 답변을 할 땐 임의로 정보를 추가해서는 안됩니다. 한국어로 답변해 주세요. 참조: [[[{context}]]], 쿼리: ((({question}))), 답변:"
answer_generation_template = 'Based on the references, please answer the query more succinctly and professionally in a full sentence. The provided references are likely to contain crucial information needed to answer the question. Each references may not be related to each other. Therefore, thoroughly check contents of each references to get useful information. The reference is delimited by triple brackets [[[]]]. The query is delimited by triple parentheses ((())). If you cannot find any useful relevant information in the references, please answer with your own knowledge. When asked with a question that possibly require an insight, carefully generate your answer based on the information given in the references. Please answer in full Korean sentence. Reference: [[[{context}]]], query: ((({question}))), answer:'#answer generation instruction 

fact_checking_template = "Now, based on the following reference, check whether the answer includes factual mistakes. The reference is delimited by triple brackets [[[]]]. The answer is delimited by triple parentheses ((())). Please only ouput Yes or No. Yes for including factual mistakes. No for not including factual mistakes. Reference: [[[{reference}]]], answer: ((({answer}))), output:"#fact checking instruction 
