Model_config:
  llm_configs: ./config/llm_alpaca.json
  device: cuda:0

Retriever_config:
  retrieve_mode: False
  data_dir: ./json_data
  Retriever_pt: ./2050iter_model.pt
  cutoff: 1000
  top_k: 3
  if_extract: False
  extract_window: 200
  extract_step: 200
  index_dir: ./index_save_dir/dense/faiss.index

output_dir: ./output
